name: Update Tranco CSV Daily

on:
  schedule:
    - cron: '0 3 * * *'  # Runs daily at 3 AM UTC
  workflow_dispatch:      # Allows manual trigger

jobs:
  update-csv:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout Repo
      uses: actions/checkout@v3

    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: '3.x'

    - name: Download and Unzip Tranco CSV
      run: |
        pip install requests
        python <<EOF
        import requests, zipfile, io

        url = "https://tranco-list.eu/top-1m.csv.zip"
        r = requests.get(url)
        z = zipfile.ZipFile(io.BytesIO(r.content))
        csv_filename = z.namelist()[0]
        content = z.read(csv_filename).decode()

        with open("top-1m.csv", "w", encoding="utf-8") as f:
            f.write(content)
        EOF

    - name: Commit and Push
      run: |
        git config --global user.name "github-actions"
        git config --global user.email "actions@github.com"
        git add top-1m.csv
        git commit -m "Update Tranco list [auto]" || echo "No changes to commit"
        git push
